import type { InstituteData } from "@/services/types";

export const instituteData: InstituteData = {
  stats: [
    { label: "Academic Departments", value: "3" },
    { label: "Experienced Faculty", value: "86+" },
    { label: "Modern Laboratories", value: "24" },
    { label: "Student Clubs", value: "12" },
  ],
  facilities: [
    { title: "Digital Library", description: "A quiet study environment with technical references, journals, and digital learning resources." },
    { title: "Computer Labs", description: "Well-equipped labs supporting programming, networking, CAD, and office automation practice." },
    { title: "Civil Workshop", description: "Surveying, materials testing, and drafting facilities for hands-on civil technology training." },
    { title: "Electrical Lab", description: "Electrical machines, power electronics, control systems, and instrumentation practice spaces." },
  ],
  achievements: [
    { title: "National Skill Competition", description: "Students consistently represent CMPI in national technical skill competitions." },
    { title: "Industry Linkage", description: "MoUs and internship pathways with leading local and national technical organizations." },
    { title: "Community Service", description: "Regular blood donation, tree plantation, and digital literacy initiatives across Cox's Bazar." },
  ],
  departments: [
    {
      id: "civil",
      slug: "civil-technology",
      title: "Civil Technology",
      shortTitle: "Civil",
      description: "Develops skilled technologists in surveying, drafting, construction management, and infrastructure maintenance.",
      overview: "Civil Technology at CMPI blends classroom theory with practical laboratory work in surveying, construction materials, estimating, and CAD-based drafting. The program prepares students for public and private sector infrastructure projects.",
      objectives: ["Apply surveying and leveling principles in field projects.", "Prepare structural and architectural drawings using modern drafting tools.", "Understand construction materials, estimation, and project supervision."],
      labs: ["Surveying Lab", "Materials Testing Lab", "AutoCAD Studio", "Construction Practice Workshop"],
      achievements: ["Best project award in regional technical exhibition", "Active participation in campus infrastructure planning"],
      careerOpportunities: ["Site Supervisor", "CAD Technician", "Survey Assistant", "Construction Estimator"],
      facultyIds: ["faculty-01", "faculty-02", "faculty-03"],
    },
    {
      id: "cst",
      slug: "computer-science-technology",
      title: "Computer Science & Technology",
      shortTitle: "CST",
      description: "Focuses on programming, networking, database systems, web development, and emerging digital technologies.",
      overview: "The Computer Science & Technology department provides industry-aligned training in software development, networking, database management, and ICT support with project-based learning.",
      objectives: ["Build software applications using modern programming practices.", "Configure and troubleshoot computer networks.", "Develop database-driven solutions for real-world problems."],
      labs: ["Programming Lab", "Networking Lab", "Database Lab", "Web Development Lab"],
      achievements: ["National programming contest participation", "Student-led campus management mini projects"],
      careerOpportunities: ["Software Developer", "Network Technician", "Database Assistant", "ICT Support Officer"],
      facultyIds: ["faculty-04", "faculty-05", "faculty-06"],
    },
    {
      id: "electrical",
      slug: "electrical-technology",
      title: "Electrical Technology",
      shortTitle: "Electrical",
      description: "Covers electrical circuits, machines, power systems, electronics, and automation fundamentals.",
      overview: "Electrical Technology trains students in installation, maintenance, testing, and troubleshooting of electrical systems with emphasis on safety and practical competence.",
      objectives: ["Analyze electrical circuits and machine operations.", "Perform safe electrical installation and maintenance tasks.", "Understand renewable energy and automation fundamentals."],
      labs: ["Electrical Machines Lab", "Power Electronics Lab", "Control Systems Lab", "Basic Electronics Lab"],
      achievements: ["Solar energy awareness project", "Technical demonstration at national polytechnic fair"],
      careerOpportunities: ["Electrical Technician", "Power Plant Assistant", "Maintenance Supervisor", "Automation Assistant"],
      facultyIds: ["faculty-07", "faculty-08", "faculty-01"],
    },
  ],
  faculty: [
    { id: "faculty-01", name: "Md. Rafiqul Islam", designation: "Principal", department: "Administration", qualification: "M.Sc. in Engineering", email: "principal@cmpi.edu.bd", phone: "+880 341 000101", specialization: ["Institutional Leadership", "Technical Education"] },
    { id: "faculty-02", name: "Engr. Nasrin Akter", designation: "Head of Department", department: "civil-technology", qualification: "B.Sc. in Civil Engineering", email: "nasrin.civil@cmpi.edu.bd", phone: "+880 341 000102", specialization: ["Structural Engineering", "Surveying"] },
    { id: "faculty-03", name: "Md. Kamal Hossain", designation: "Lecturer", department: "civil-technology", qualification: "B.Sc. in Civil Engineering", email: "kamal.civil@cmpi.edu.bd", phone: "+880 341 000103", specialization: ["Construction Management", "AutoCAD"] },
    { id: "faculty-04", name: "Tanjila Rahman", designation: "Head of Department", department: "computer-science-technology", qualification: "M.Sc. in CSE", email: "tanjila.cst@cmpi.edu.bd", phone: "+880 341 000104", specialization: ["Software Engineering", "Database Systems"] },
    { id: "faculty-05", name: "Md. Shahriar Kabir", designation: "Lecturer", department: "computer-science-technology", qualification: "B.Sc. in CSE", email: "shahriar.cst@cmpi.edu.bd", phone: "+880 341 000105", specialization: ["Networking", "Web Development"] },
    { id: "faculty-06", name: "Farhana Yeasmin", designation: "Instructor", department: "computer-science-technology", qualification: "M.Sc. in ICT", email: "farhana.cst@cmpi.edu.bd", phone: "+880 341 000106", specialization: ["Programming", "Multimedia"] },
    { id: "faculty-07", name: "Engr. Mizanur Rahman", designation: "Head of Department", department: "electrical-technology", qualification: "B.Sc. in Electrical Engineering", email: "mizan.electrical@cmpi.edu.bd", phone: "+880 341 000107", specialization: ["Power Systems", "Electrical Machines"] },
    { id: "faculty-08", name: "Sumaiya Islam", designation: "Lecturer", department: "electrical-technology", qualification: "B.Sc. in EEE", email: "sumaiya.electrical@cmpi.edu.bd", phone: "+880 341 000108", specialization: ["Electronics", "Control Systems"] },
  ],
  notices: [
    { id: "notice-01", title: "Admission Application Open for 2026-2027 Session", category: "Admission", date: "2026-06-10", summary: "Online and offline application procedures are now available for diploma admission.", details: "Applicants must submit academic transcripts, citizenship documents, passport-size photographs, and the prescribed application fee before the announced deadline.", fileUrl: "/notices/admission-2026.pdf" },
    { id: "notice-02", title: "Mid-Term Examination Routine Published", category: "Exam", date: "2026-06-05", summary: "The mid-term examination routine for all departments has been published.", details: "Students are advised to collect the routine from the academic section and follow the seating plan announced one day before the examination.", fileUrl: "/notices/midterm-routine.pdf" },
    { id: "notice-03", title: "Eid-ul-Adha Holiday Announcement", category: "Holiday", date: "2026-05-28", summary: "The institute will remain closed for Eid-ul-Adha vacation as per government guidelines.", details: "Regular academic activities will resume according to the academic calendar published by the academic section.", fileUrl: "/notices/eid-holiday.pdf" },
    { id: "notice-04", title: "Tender Notice for Laboratory Equipment", category: "Tender", date: "2026-05-20", summary: "Quotations are invited from eligible suppliers for laboratory equipment procurement.", details: "Interested suppliers must submit sealed quotations with technical specifications, warranty terms, and valid trade license copies.", fileUrl: "/notices/tender-lab-equipment.pdf" },
  ],
  events: [
    { id: "event-01", title: "Technical Career Fair 2026", date: "2026-07-15", time: "10:00 AM - 4:00 PM", venue: "Central Auditorium", category: "Academic", status: "Upcoming", summary: "Industry partners will showcase career pathways, internships, and technical training opportunities.", details: "Students from all departments are encouraged to bring resumes and attend employer briefing sessions." },
    { id: "event-02", title: "National Technology Day Celebration", date: "2026-10-28", time: "9:00 AM - 1:00 PM", venue: "Campus Ground", category: "Cultural", status: "Upcoming", summary: "A day-long celebration featuring projects, cultural programs, and technical demonstrations.", details: "Departments will present student projects and innovation models related to national development." },
    { id: "event-03", title: "Web Development Workshop", date: "2026-06-22", time: "2:00 PM - 5:00 PM", venue: "Computer Lab 2", category: "Workshop", status: "Upcoming", summary: "Hands-on workshop on responsive web development and deployment fundamentals.", details: "Participants will learn HTML, CSS, JavaScript, and deployment workflows using practical exercises." },
    { id: "event-04", title: "Annual Sports Meet 2026", date: "2026-04-18", time: "8:00 AM - 5:00 PM", venue: "Campus Sports Field", category: "Sports", status: "Past", summary: "Inter-department sports competitions were held with enthusiastic student participation.", details: "Civil Technology secured the championship title, while CST won the runners-up position." },
  ],
  blogs: [
    { id: "blog-01", slug: "why-polytechnic-education-matters", title: "Why Polytechnic Education Matters for National Development", excerpt: "A practical look at how diploma engineers contribute to infrastructure, ICT, and industrial growth.", content: "Polytechnic education connects classroom learning with workplace-ready skills. CMPI emphasizes laboratory practice, project work, and industry exposure so graduates can contribute quickly to national development priorities.", author: "Academic Cell", date: "2026-06-01", category: "Academics", readTime: "5 min read", relatedIds: ["blog-02", "blog-03"] },
    { id: "blog-02", slug: "campus-life-at-cmpi", title: "Campus Life at CMPI: Learning Beyond the Classroom", excerpt: "Explore clubs, events, labs, and student support services that shape daily campus life.", content: "CMPI campus life combines academic rigor with co-curricular activities. Student clubs, technical exhibitions, community service, and sports events help learners build leadership, teamwork, and communication skills.", author: "Student Welfare", date: "2026-05-18", category: "Campus", readTime: "4 min read", relatedIds: ["blog-01", "blog-03"] },
    { id: "blog-03", slug: "admission-guide-2026", title: "Admission Guide 2026: What Applicants Should Know", excerpt: "A concise checklist for documents, eligibility, fees, and important admission dates.", content: "Prospective students should review eligibility criteria, prepare academic transcripts, collect citizenship documents, and follow the published application schedule. The admission office provides support desks during the application period.", author: "Admission Office", date: "2026-05-10", category: "Admission", readTime: "6 min read", relatedIds: ["blog-01", "blog-02"] },
  ],
  albums: [
    { id: "album-01", title: "Campus Overview", count: 24, description: "Academic buildings, central field, library, and common spaces.", accent: "from-emerald-700 to-emerald-500" },
    { id: "album-02", title: "Laboratories", count: 36, description: "Civil, CST, and electrical laboratories with practical learning spaces.", accent: "from-amber-500 to-yellow-300" },
    { id: "album-03", title: "Student Activities", count: 18, description: "Clubs, cultural programs, sports, and community initiatives.", accent: "from-slate-800 to-slate-600" },
  ],
  resources: [
    { id: "resource-01", title: "Academic Calendar 2026", type: "PDF", description: "Semester timeline, examination windows, holidays, and result publication schedule.", updatedAt: "2026-06-01" },
    { id: "resource-02", title: "Class Routine Template", type: "XLS", description: "Department-wise class routine template for students and teachers.", updatedAt: "2026-05-25" },
    { id: "resource-03", title: "Admission Application Form", type: "DOC", description: "Printable admission form for offline submission.", updatedAt: "2026-05-20" },
    { id: "resource-04", title: "Student Portal Login", type: "Link", description: "Access academic records, notices, and downloadable forms.", updatedAt: "2026-06-05" },
  ],
  faqs: [
    { question: "Who is eligible for diploma admission?", answer: "Applicants must meet the current Bangladesh Technical Education Board eligibility criteria and submit required academic documents." },
    { question: "Does CMPI provide hostel facilities?", answer: "Hostel-related information is announced by the institute authority according to seat availability and government guidelines." },
    { question: "How can I collect a notice copy?", answer: "Notices can be downloaded from the Notice Board page or collected from the relevant administrative office with proper identification." },
    { question: "Are practical labs available for all departments?", answer: "Yes. CMPI maintains department-specific labs and workshops for Civil, CST, and Electrical Technology programs." },
  ],
};
